=== skedgo/regions/schemas/pt-static-feed.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://region-registry.skedgo.com/pt-static-feed.schema.json",
  "title": "Public Transport Data Feed",
  "description": "Public Transport Data Feed specification.",
  "type": "object",
  "properties": {
    "id": {
      "description": "Unique identifier for this feed. Recommended format is ISO Country Code + Provider name; for example au-tfnsw. For multi country feeds, recommended format is Continent Code + Provider name; for example eu-flixbus.",
      "type": "string",
      "pattern": "^[a-z]{2}-(([a-z]|-)+)$"
    },  
    "name": {
      "description": "Human friendly name for this feed.",
      "type": "string",
      "minLength": 1
    },
    "type": {
      "description": "Type of this feed.",
      "enum": ["gtfs", "netex", "txc"],
      "default": "gtfs"
    },
    "source": {
      "description": "Details about how to get this feed.",
      "type": "object",
      "properties": {
        "url": {
          "description": "URL where this feed can downloaded.",
          "type": "string"
        },
        "headers": {
          "description": "HTTP headers to include in order to download this feed.",
          "type": "object",
          "additionalProperties": {"type": "string"}
        },
        "checkCertificate": {
          "description": "(Only for HTTPS requests) Whether to check or not the https certificates when downloading this feed.",
          "type": "boolean",
          "default": true
        },
        "authentication": {
          "description": "Authentication details.",
          "type": "object",
          "properties": {
            "type": {
              "description": "Authentication mode type",
              "enum": [ "header" , "query", "userpass" ]
            },
            "description": {
              "description": "Description of this authentication mode type",
              "type": "string"
            }
          }
        },
        "apiInformation": {
          "description": "Information about the API where this feed is published.",
          "type": "object",
          "properties": {
            "name": {
              "description": "Name or description of this API",
              "type": "string"
            },
            "url": {
              "description": "Website of the API",
              "type": "string"
            }
          },
          "required": [ "name" , "url" ]
        }
      }, 
      "required": [ "url" ]
    },
    "dataProvider": {
      "description": "Data provider details.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the provider",
          "type": "string"
        },
        "url": {
          "description": "Website of the provider",
          "type": "string"
        }
      },
      "required": [ "name" , "url" ]
    },
    "license": {
      "description": "License details.",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of this license",
          "type": "string"
        },
        "url": {
          "description": "License's URL",
          "type": "string"
        }
      },
      "required": [ "name", "url" ]
    },
    "realtime": {
      "description": "Real time feeds associated to this feed. Each item should match with a real-time-feed id.",
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "minItems": 1
    },
    "excludedFiles": {
      "description": "List of the files to exclude when parsing this feed.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "includeOnlyFiles": {
      "description": "List of the files to include when parsing this feed.",
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [ "id", "name", "source", "dataProvider" ]
}

=== skedgo/regions/pt-static-feeds/us-santaclaritatransit.json
{
  "id": "us-santaclaritatransit",
  "name": "Santa Clarita Transit",
  "type": "gtfs",
  "source": {
    "url": "https://apps.santaclaritatransit.com/rtt/public/utility/gtfs.aspx"
  },
  "dataProvider": {
    "name": "Santa Clarita Transit",
    "url": "https://apps.santaclaritatransit.com"
  }
}

=== skedgo/regions/publictransportfeeds/ar-bacolectivos.json
{
  "id": "ar-bacolectivos",
  "name": "Colectivos",
  "type": "gtfs",
  "source": {
    "url": "https://apitransporte.buenosaires.gob.ar/colectivos/feed-gtfs?client_id=d3d3c80dc41a40dbb13dc2654c9e01ca&client_secret=048bcD1A07DD4F32BdF0AdC5D46456af",
    "apiInformation": {
      "name": "API Transporte – Datos Abiertos",
      "url": "https://apitransporte.buenosaires.gob.ar/console/"
    }
  },
  "dataProvider": {
    "name": "Gobierno de la Ciudad de Buenos Aires",
    "url": "https://www.buenosaires.gob.ar/"
  },
  "license": {
    "name": "Licence: Creative Commons Atribución 2.5 (Argentina)",
    "url": "https://creativecommons.org/licenses/by/2.5/ar/legalcode"
  },
  "realtime": [ "ar-babusrt" ]
}

=== skedgo/regions/pt-static-feeds/us-vctc.json
{
  "id": "us-vctc",
  "name": "Ventura County Transportation Commission",
  "type": "gtfs",
  "source": {
    "url": "https://transitfeeds.com/p/ventura-county-transportation-commission/792/latest/download"
  },
  "dataProvider": {
    "name": "Ventura County Transportation Commission",
    "url": "https://www.goventura.org/es/"
  }
}

=== skedgo/regions/pt-static-feeds/us-toakstransit.json
{
  "id": "us-toakstransit",
  "name": "Thousand Oaks Transit",
  "type": "gtfs",
  "source": {
    "url": "https://data.trilliumtransit.com/gtfs/thousandoaks-ca-us/thousandoaks-ca-us.zip"
  },
  "dataProvider": {
    "name": "Thousand Oaks Transit",
    "url": "https://www.toaks.org/departments/public-works/transit"
  }
}

=== skedgo/regions/pt-static-feeds/us-wsf.json
{
  "id": "us-wsf",
  "name": "Washington State Ferries",
  "type": "gtfs",
  "source": {
    "url": "https://business.wsdot.wa.gov/Transit/csv_files/wsf/google_transit.zip"
  },
  "dataProvider": {
    "name": "Washington State Ferries",
    "url": "https://wsdot.wa.gov/travel/washington-state-ferries"
  }
}

=== skedgo/regions/pt-static-feeds/us-sunshinebus.json
{
  "id": "us-sunshinebus",
  "name": "Sunshine Bus",
  "type": "gtfs",
  "source": {
    "url": "http://data.trilliumtransit.com/gtfs/sunshinebuscompany-fl-us/sunshinebuscompany-fl-us.zip"
  },
  "dataProvider": {
    "name": "Sunshine Bus",
    "url": "https://www.staugbch.com/community/page/public-transportation"
  }
}

=== skedgo/regions/pt-static-feeds/ar-bacolectivos.json
{
  "id": "ar-bacolectivos",
  "name": "Colectivos",
  "type": "gtfs",
  "source": {
    "url": "https://apitransporte.buenosaires.gob.ar/colectivos/feed-gtfs",
    "apiInformation": {
      "name": "API Transporte – Datos Abiertos",
      "url": "https://apitransporte.buenosaires.gob.ar/console/"
    },
    "authentication": {
      "type": "query",
      "description": "client_id and client_secret query parameters must be provided."
    }
  },
  "dataProvider": {
    "name": "Gobierno de la Ciudad de Buenos Aires",
    "url": "https://www.buenosaires.gob.ar/"
  },
  "license": {
    "name": "Licence: Creative Commons Atribución 2.5 (Argentina)",
    "url": "https://creativecommons.org/licenses/by/2.5/ar/legalcode"
  },
  "realtime": [ "ar-babusrt" ]
}

=== skedgo/regions/pt-static-feeds/us-southportlandbus.json
{
  "id": "us-southportlandbus",
  "name": "SouthPortlandBus",
  "type": "gtfs",
  "source": {
    "url": "http://www.smttracker.com/downloads/gtfs/south-portland-me-us.zip"
  },
  "dataProvider": {
    "name": "City of South Portland",
    "url": "https://www.southportland.org/departments/bus-transportation/"
  }
}
